config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get '/profile', to: 'profiles#show', as: :profile

  get '/search', to: 'restaurants#search', as: :search

  resources :restaurants do
    resources :favorite_restaurants, only: [:create, :destroy]
    resources :facts do
      resources :likes, only: :create
    end
  end

  get '/surprise/:id', to: 'surprise#show', as: :surprise

  get '/about_me', to: 'welcome#about_me', as: :about_me

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @favorite_restaurants = current_user.restaurants
    @preferences = current_user.preferences
  end
end

app/helpers/profile_helper.rb
module ProfileHelper

  def find_fave_restaurant(restaurant)
    FavoriteRestaurant.find_by(restaurant_id: restaurant.id, user_id: current_user.id)
  end

end

app/views/profiles/_favorite_restaurants.html.erb
<div class="display_restaurant">
  <div class="one_fourth">
    <img src="<%= restaurant.photo_uri %>"/>
  </div>
  <div class="one_third">
    <div class="restaurant_info">
      <p><%= link_to restaurant.name, restaurant_path(restaurant) %>

      <p class="smaller"><%= restaurant.location %></p>

      <p class="smaller"><%= restaurant.rating %> out of 5 stars</p>
    </div>
    <% restaurant.dietary_option_list.each do |option| %>
      <div class="option_tags"><%= option %></div>
    <% end %>
    <div>
      <%= link_to 'Remove from favorites', restaurant_favorite_restaurant_path(restaurant_id: restaurant.id, id: find_fave_restaurant(restaurant)),
                  method: 'delete', data: {confirm: "Are you sure?"} %>
    </div>
  </div>
</div>

app/views/profiles/_my_preferences.html.erb
<li><%= preference.preference_name %></li>

app/views/profiles/show.html.erb
<h2>My Profile</h2>

<h4>My favorite restaurants: </h4>
  <%= render partial: "favorite_restaurants", collection: @favorite_restaurants, as: :restaurant %>

<h4>My preferences: </h4>
<ul>
  <%= render partial: "my_preferences", collection: @preferences, as: :preference %>
</ul>