config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get '/profile', to: 'profiles#show', as: :profile

  get '/search', to: 'restaurants#search', as: :search

  resources :restaurants do
    resources :favorite_restaurants, only: [:create, :destroy]
    resources :facts do
      resources :likes, only: :create
    end
  end

  get '/surprise/:id', to: 'surprise#show', as: :surprise

  get '/about_me', to: 'welcome#about_me', as: :about_me

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  DIETARY_OPTIONS = ["gluten free options", "dairy free options", "vegan options", "vegetarian options",
                     "organic ingredients", "grass fed beef", "100% gluten free",
                     "100% vegetarian", "100% vegan",]

  acts_as_taggable_on :dietary_options

  validates :name, presence: true, uniqueness: {case_sensitive: false, scope: :location}
  validates :dietary_option_list, presence: {message: "You must check at least 1 diet option"}

  has_many :favorite_restaurants, dependent: :destroy
  has_many :users, through: :favorite_restaurants

  has_many :facts

  def self.search(location, tags)
    scope = where(location: location)
    scope = scope.tagged_with(tags) if tags.present?
    scope
  end

  def facts
    facts = super
    facts.sort { |a, b| b.get_likes.size <=> a.get_likes.size }
  end

  def num_favorites
    users.length
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def search
    @restaurants = Restaurant.search(params[:homepage_location], params.fetch(:option, {}).keys)
    Preference.save_preferences_for(current_user, params[:option]) if params[:save]
    if params[:surprise]
      @restaurant = @restaurants.sample
      redirect_to restaurant_path(@restaurant)
    else
      @latitude, @longitude = APIRequest.new.get_lat_lng(params[:homepage_location])
      render :search_results
    end
  end

  def new
    if user_signed_in?
      @restaurant = Restaurant.new
    else
      render :errors
    end
  end

  def show
    @favorite_restaurant = FavoriteRestaurant.new
    if Restaurant.exists?(params[:id])
      @restaurant = Restaurant.find(params[:id])
      @fact = Fact.new
    else
      render 'errors/404', status: 404
    end
  end

  def edit
    if user_signed_in?
      @restaurant = Restaurant.find(params[:id])
    else
      not_found
    end
  end

  def create
    @restaurant = Restaurant.new(restaurant_attributes)
    if @restaurant.name?
      api_response = APIRequest.new.get_first_result(@restaurant.name, @restaurant.location)
      search_attributes = api_response.to_h
      @restaurant.attributes = search_attributes
    end

    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(restaurant_attributes)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    Restaurant.find(params[:id]).destroy
    redirect_to root_path
  end

  private

  def restaurant_attributes
    attributes = params.require(:restaurant).permit(:address, :location, :website, :name)
    attributes[:name] = attributes[:name].titleize
    attributes[:dietary_option_list] = params.fetch(:option, {}).keys.join(", ")
    attributes
  end

end

app/helpers/restaurants_helper.rb
module RestaurantsHelper

  def fact_user_name(fact)
    user = User.find(fact.user_id).email
    #get just the first part without the domain name
    user[0...(user.index('@'))]
  end

end

app/views/restaurants/_add_fact_form.html.erb
<%= form_for [@restaurant, @fact] do |f| %>
  <%= f.label :body, 'Enter your tidbit: ', class: 'smaller' %>
  <%= f.text_field :body %>
  <%= f.submit "Add Tidbit" %>
<% end %>

app/views/restaurants/_favorite_restaurant_button.html.erb
<%= form_for [@restaurant, @favorite_restaurant] do |f| %>
  <%= f.submit "Favorite this restaurant", class: "favorite_button" %>
<% end %>

app/views/restaurants/_ratings_arrows.html.erb
<div id="arrows_div">

  <a href="/restaurants/<%= @restaurant.id %>/facts/<%= fact.id %>}/likes?up=true" data-method="post"> <%= image_tag("up_arrow.png", id: "up_arrow", class: "arrows") %></a>
  <p class="arrows" id="votes"><%= fact.get_likes.size %></p>
  <a href="/restaurants/<%= @restaurant.id %>/facts/<%= fact.id %>}/likes?down=true" data-method="post"><%= image_tag("down_arrow.png", id: "down_arrow", class: "arrows") %></a>

</div>

app/views/restaurants/_restaurant.html.erb
<div class="display_restaurant">
  <div class="one_fourth">
    <img src="<%= restaurant.photo_uri %>"/>
  </div>
  <div class="one_third">
    <div class="restaurant_info">
      <p><a href="/restaurants/<%= restaurant.id %>"><%= restaurant.name %> </a></p>

      <p class="smaller"><%= restaurant.location %></p>


      <div class="star" data-rating="<%= restaurant.rating %>"></div>
      <div class="star-rating-in-words"><%= restaurant.rating %> stars</div>
    </div>
    <% restaurant.dietary_option_list.each do |option| %>
      <div class="option_tags"><%= option %></div>
    <% end %>
  </div>
</div>
<% counter +=1 %>
  <% if counter.even? %>
  <hr>
<% end %>

<script>
  $(document).ready(function(){
    my_restaurant = <%= restaurant.to_json.html_safe %>;
    StarRating.initialize(my_restaurant);
  });
</script>

app/views/restaurants/_restaurant_dietary_option_tags.html.erb
<div class="option_tags_big"><%= option %></div>

app/views/restaurants/_restaurant_facts.html.erb
  <%= render 'restaurants/ratings_arrows', fact: fact %>
  <div id="facts_p">
    <p><%= fact.body %></p>

    <p class="smaller">
      Added by <%= fact_user_name(fact) %> <%= time_ago_in_words(fact.created_at) %> ago
      <% if current_user == fact.user %>
        <%= link_to 'Delete my tidbit', restaurant_fact_path(@restaurant, fact), data: {confirm: "Are you sure?"}, :method => :delete %>
      <% end %>
    </p>
  </div>
  <p></p>

app/views/restaurants/edit.html.erb
  <% if @restaurant && @restaurant.errors %>
    <% @restaurant.errors.full_messages.each do |message| %>
      <p class="error"><%= message %></p>
    <% end %>
  <% end %>


<%= form_for @restaurant, url: "/restaurants/#{@restaurant.id}" do |f| %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :website %>
    <%= f.text_field :website %>
  </p>

  <p>
    <%= f.label :location %>
    <%= f.select :location, [['Highlands, Denver', 'Highlands, Denver'], ['Pearl Street, Boulder', 'Pearl Street, Boulder']] %>
  </p>

  <% Restaurant::DIETARY_OPTIONS.each do |option| %>
    <% if @restaurant.dietary_option_list.include? option %>
    <% checked = true  %>
      <% end %>

    <p>
      <%= check_box_tag "option[#{option}]", "0", checked %> <%= option %>
    </p>
  <% end %>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

app/views/restaurants/errors.html.erb
<h2>You do not have permission to be here.</h2>

<h2>or</h2>

<h2>There was an error</h2>

app/views/restaurants/new.html.erb
<h2>Add a Restaurant</h2>

<% if @restaurant %>
  <% if @restaurant.errors %>
    <% @restaurant.errors.full_messages.each do |message| %>
      <p class="error"><%= message %></p>
    <% end %>
  <% end %>
<% end %>


<%= form_for @restaurant do |f| %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :location %>
    <%= f.select :location, [['Highlands, Denver', 'Highlands, Denver'], ['Pearl Street, Boulder', 'Pearl Street, Boulder']] %>
  </p>

  <% Restaurant::DIETARY_OPTIONS.each do |option| %>
    <% if @restaurant.dietary_option_list.include? option %>
      <% checked = true  %>
    <% end %>
    <p>
      <label>
        <%= check_box_tag "option[#{option}]","0", checked %>
        <%= option %>
      </label>
    </p>
  <% end %>

  <p>Optional fields: </p>

  <p>
    <%= f.label :website %>
    <%= f.text_field :website %>
  </p>

  <p>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.submit "Add this Restaurant" %>
  </p>
<% end %>

app/views/restaurants/search_results.html.erb
<h2>Here ya go...</h2>
<div id="map_canvas" data-coordinates='{"latitude":<%= @latitude %>, "longitude": <%= @longitude %>}' data-restaurants='<%= @restaurants.to_json.html_safe %>'></div>

<%= render partial: "restaurants/restaurant", collection: @restaurants, locals: {counter: 0} %>

<% if user_signed_in? %>
  <p>
    <%= link_to 'Add a Restaurant', new_restaurant_path %>
  </p>
<% end %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<div class="show_sections">
  <div class="one_half">
    <img id="restaurant_photo" src="<%= @restaurant.photo_uri %>"/>
  </div>

  <div id="restaurant_info" class="one_half">


    <p class="neighborhood">Neighborhood: <%= @restaurant.location %></p>

    <p class="smaller address">
      <span><%= @restaurant.address %></span>
      <a href="http://maps.google.com/maps?q=<%= @restaurant.address %>" target="_blank">
        Show me on the map »
      </a>
    </p>

    <p class="smaller"><a href="<%= @restaurant.website %>" target="_blank">Restaurant Website »</a></p>
    <% if @restaurant.rating %>

      <div class="star"></div>
      <div class="star-rating-in-words"><%= @restaurant.rating %> stars from Google Reviews</div>
      <p></p>
    <% end %>



    <div>
      <%= render 'restaurants/favorite_restaurant_button' if user_signed_in? %>

      <p class="new_favorite_restaurant">
        <%= @restaurant.num_favorites %>
        <%= image_tag("heart.png", class: "heart_img") %>
      </p>
    </div>

  </div>
</div>

<div class="show_sections">
  <%= render partial: "restaurants/restaurant_dietary_option_tags", collection: @restaurant.dietary_option_list, as: :option %>
  <p></p>
  <hr>
  <p class="bold">Tidbits people have shared about <%= @restaurant.name %>:</p>

  <div class="facts">
    <% if @restaurant.facts.empty? %>
      <p class="not_bold">(Be the first to add something.)</p>
    <% else %>
      <%= render partial: "restaurant_facts", collection: @restaurant.facts, as: :fact %>
    <% end %>
  </div>
  <p></p>

  <p class="bold" id="smaller">Have something about this restaurant you want to share?</p>
  <% if user_signed_in? %>
    <%= render "add_fact_form" %>
  <% else %>
    <p>You must <%= link_to 'sign in', new_user_session_path %> if you want to share something.</p>
  <% end %>
</div>
<br>
<br>
<% if user_signed_in? %>

  <%= link_to 'Edit Restaurant Information', edit_restaurant_path(@restaurant), class: 'link_buttons' %>
  <% if current_user.admin? %>

    <%= form_for @restaurant, url: "/restaurants/#{@restaurant.id}", method: "delete" do |f| %>
      <%= f.submit :delete, data: {confirm: "Are you sure?"} %>
    <% end %>
  <% end %>
<% end %>

<script>
  $(document).ready(function(){

    var restaurant = <%= @restaurant.to_json.html_safe %>
    $('.star').raty({
      readOnly: true,
      score: restaurant.rating,
      path: '/assets'
    });

  });
</script>