config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get '/profile', to: 'profiles#show', as: :profile

  get '/search', to: 'restaurants#search', as: :search

  resources :restaurants do
    resources :favorite_restaurants, only: [:create, :destroy]
    resources :facts do
      resources :likes, only: :create
    end
  end

  get '/surprise/:id', to: 'surprise#show', as: :surprise

  get '/about_me', to: 'welcome#about_me', as: :about_me

end

app/views/layouts/_user_widget.erb
<% if user_signed_in? %>
  <li class="signed-in-message">Welcome <%= current_user.email %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picky Eater</title>
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
  <script src="https://maps.googleapis.com/maps/api/js"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
  <header>
    <nav>
      <div id="nav_container">
        <ul>

          <%= render 'layouts/user_widget' %>
          <li><%= link_to 'My Profile', profile_path if user_signed_in? %></li>
          <li><a href="/">New Search</a></li>
        </ul>
      </div>
    </nav>
    <div id="header_container">
      <h1><span><%= link_to 'Picky Eater', root_path %></span></h1>

      <h3><span>Find restaurants in the Denver/Boulder area <br>that suit your dietary preferences.</span>
      </h3>
    </div>
  </header>

  <div id="sign_in_flash">
    <p class="notice"><%= notice %></p>

    <p class="alert"><%= alert %></p>
  </div>


  <div id="main">
    <div id="main_container">
      <%= yield %>
    </div>
  </div>

  <footer>
    <div id="footer_container">
      <%= link_to 'Rachel Logie 2014', about_me_path %>
    </div>
  </footer>
</div>
</body>
</html>